export const LANG_CONNECTED      = 'Connected'
export const LANG_DISCONNECTED   = 'Not Connected'
export const LANG_ALARM_BTN1     = 'Alarm 1'
export const LANG_ALARM_BTN2     = 'Alarm 2'
export const LANG_FIND_BTN1      = 'Find 1'
export const LANG_FIND_BTN2      = 'Find 2'
export const LANG_LATITUDE       = 'Latitude'
export const LANG_LONGITUDE      = 'Longitude'
export const LANG_BATTERY        = 'Battery'
export const LANG_SAT_TRACKED    = 'Satelites Tracked'
export const LANG_SAT_TOTAL      = 'Satelites Total'
export const LANG_DEVICE_01      = 'Device 01'
export const LANG_DEVICE_02      = 'Device 02'


